<?php

declare(strict_types=1);

namespace App\Core;

/** Helpers for the first-run wizard (public/setup.php). */
final class Installer
{
    /**
     * Validate the setup form.
     *
     * @return array{0: list<string>, 1: array<string,mixed>} [errors, cleaned values]
     */
    public static function validate(Request $req): array
    {
        $errors = [];
        $v = [
            'app_name'     => trim((string) $req->post('app_name')),
            'db_host'      => trim((string) $req->post('db_host')),
            'db_port'      => (int) $req->post('db_port'),
            'db_name'      => trim((string) $req->post('db_name')),
            'db_user'      => trim((string) $req->post('db_user')),
            'db_pass'      => (string) $req->post('db_pass'),
            'idle_minutes' => (int) $req->post('idle_minutes'),
            'migrate'      => $req->post('migrate') === '1',
            'admin_user'   => trim((string) $req->post('admin_user')),
            'admin_first'  => trim((string) $req->post('admin_first')),
            'admin_last'   => trim((string) $req->post('admin_last')),
            'admin_email'  => trim((string) $req->post('admin_email')),
            'admin_pass'   => (string) $req->post('admin_pass'),
            'admin_pass2'  => (string) $req->post('admin_pass2'),
        ];

        if ($v['app_name'] === '' || strlen($v['app_name']) > 64) {
            $errors[] = 'Enter an application name (up to 64 characters).';
        }
        // Strict patterns also keep ";" and "=" out of the PDO DSN string.
        if (!preg_match('/^[A-Za-z0-9._:\-\[\]]{1,255}$/', $v['db_host'])) {
            $errors[] = 'Enter a valid database host name or IP address.';
        }
        if ($v['db_port'] < 1 || $v['db_port'] > 65535) {
            $errors[] = 'The database port must be between 1 and 65535.';
        }
        if (!preg_match('/^[A-Za-z0-9_$\-]{1,64}$/', $v['db_name'])) {
            $errors[] = 'Enter a valid database name (letters, numbers, _ $ -).';
        }
        if ($v['db_user'] === '') {
            $errors[] = 'Enter the database user.';
        }
        if ($v['idle_minutes'] < 1 || $v['idle_minutes'] > 1440) {
            $errors[] = 'The inactivity timeout must be between 1 and 1440 minutes.';
        }

        $wantsAdmin = $v['admin_user'] !== '' || $v['admin_pass'] !== '';
        if ($wantsAdmin) {
            if (!preg_match('/^[A-Za-z0-9._@-]{1,16}$/', $v['admin_user'])) {
                $errors[] = 'Administrator username: up to 16 letters, numbers or . _ @ -';
            }
            if (strlen($v['admin_pass']) < 10) {
                $errors[] = 'The administrator password must be at least 10 characters.';
            }
            if ($v['admin_pass'] !== $v['admin_pass2']) {
                $errors[] = 'The administrator passwords do not match.';
            }
            if ($v['admin_email'] !== '' && !filter_var($v['admin_email'], FILTER_VALIDATE_EMAIL)) {
                $errors[] = 'Enter a valid administrator email address (or leave it blank).';
            }
        }
        $v['wants_admin'] = $wantsAdmin;

        return [$errors, $v];
    }

    /** The structure written to config/config.php. */
    public static function configValues(array $v): array
    {
        return [
            'app' => ['name' => $v['app_name'], 'debug' => false],
            'db'  => [
                'host'    => $v['db_host'],
                'port'    => $v['db_port'],
                'name'    => $v['db_name'],
                'user'    => $v['db_user'],
                'pass'    => $v['db_pass'],
                'charset' => 'utf8mb4',
                'dsn'     => null,
            ],
            'session' => [
                'name'         => 'assets_session',
                'idle_timeout' => $v['idle_minutes'] * 60,
                'secure'       => null,
            ],
        ];
    }

    /** PHP source for the config file. var_export() escapes values, so no input can inject code. */
    public static function configPhp(array $values): string
    {
        return "<?php\n// Generated by setup.php on " . date('Y-m-d H:i:s') . ".\n// Contains the database password: keep this file private and out of version control.\n\nreturn "
            . var_export($values, true) . ";\n";
    }

    /**
     * Create the config file. Opens with mode "x" (create-only), so an existing
     * config can never be overwritten, even by a concurrent request.
     *
     * @throws \RuntimeException if the file cannot be created
     */
    public static function writeConfig(string $php): void
    {
        $path = Config::path();
        $dir = dirname($path);
        if (!is_dir($dir) || !is_writable($dir)) {
            throw new \RuntimeException("The folder {$dir} is not writable by the web server.");
        }
        $fh = @fopen($path, 'x');
        if ($fh === false) {
            throw new \RuntimeException("Could not create {$path} (it may already exist).");
        }
        $ok = fwrite($fh, $php) === strlen($php);
        fclose($fh);
        @chmod($path, 0640);
        if (!$ok) {
            @unlink($path);
            throw new \RuntimeException("Could not write to {$path}.");
        }
    }

    /** True if the connection failed only because the named database doesn't exist (MySQL error 1049). */
    public static function isUnknownDatabase(\PDOException $e): bool
    {
        return (int) $e->getCode() === 1049 || str_contains($e->getMessage(), '[1049]');
    }

    /**
     * Create the database named in the setup values (the name was validated against
     * a strict pattern, so quoting it in backticks is safe).
     *
     * @throws \RuntimeException
     */
    public static function createDatabase(array $v): void
    {
        try {
            $pdo = new \PDO(
                sprintf('mysql:host=%s;port=%d;charset=utf8mb4', $v['db_host'], $v['db_port']),
                $v['db_user'],
                $v['db_pass'],
                [\PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION]
            );
            $pdo->exec('CREATE DATABASE `' . $v['db_name'] . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
        } catch (\PDOException $e) {
            throw new \RuntimeException(
                'The database "' . $v['db_name'] . '" does not exist and could not be created (the user needs the CREATE privilege, '
                . 'or create it yourself first): ' . $e->getMessage()
            );
        }
    }

    /** Number of tables in the connected database. */
    public static function tableCount(Database $db): int
    {
        return (int) $db->value('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema = DATABASE()');
    }

    /**
     * Run a SQL dump (e.g. assets.schema.sql) statement by statement. Returns the statement count.
     *
     * @throws \RuntimeException
     */
    public static function importSchema(Database $db, string $file): int
    {
        $sql = is_file($file) ? file_get_contents($file) : false;
        if ($sql === false) {
            throw new \RuntimeException('The schema file assets.schema.sql was not found next to the application.');
        }
        $statements = Migrator::splitStatements($sql);
        try {
            foreach ($statements as $statement) {
                $db->pdo()->exec($statement);
            }
        } catch (\PDOException $e) {
            throw new \RuntimeException('Importing assets.schema.sql failed: ' . $e->getMessage(), 0, $e);
        }
        return count($statements);
    }

    /**
     * Create an administrator, or promote and reset the password of an existing
     * user with that username. Returns 'created' or 'updated'.
     *
     * @throws \RuntimeException
     */
    public static function saveAdmin(Database $db, array $v): string
    {
        $hash = password_hash($v['admin_pass'], PASSWORD_DEFAULT);
        $pdo = $db->pdo();
        $pdo->beginTransaction();
        try {
            $existing = $db->one('SELECT user_id FROM users WHERE username = ?', [$v['admin_user']]);

            if ($existing !== null) {
                $userId = (string) $existing['user_id'];
                $db->execute('UPDATE users SET password = ?, admin = 1 WHERE user_id = ?', [$hash, $userId]);
                $result = 'updated';
            } else {
                $userId = $v['admin_user'];
                if ($db->one('SELECT 1 FROM users WHERE user_id = ?', [$userId]) !== null) {
                    throw new \RuntimeException("A different user already has the ID \"{$userId}\".");
                }
                $db->execute(
                    'INSERT INTO users (user_id, username, password, firstname, lastname, email, department_id, admin, timezone, lastlogin)
                     VALUES (?, ?, ?, ?, ?, ?, 0, 1, ?, ?)',
                    [$userId, $v['admin_user'], $hash, $v['admin_first'], $v['admin_last'], $v['admin_email'], 'UTC', date('Y-m-d H:i:s')]
                );
                $result = 'created';
            }

            // A narrow legacy column in non-strict SQL mode would silently truncate the hash.
            if ($db->value('SELECT password FROM users WHERE user_id = ?', [$userId]) !== $hash) {
                throw new \RuntimeException('The users.password column is too narrow. Tick "apply database updates" and try again.');
            }
            $pdo->commit();
            return $result;
        } catch (\Throwable $e) {
            if ($pdo->inTransaction()) {
                $pdo->rollBack();
            }
            throw $e instanceof \RuntimeException ? $e : new \RuntimeException($e->getMessage(), 0, $e);
        }
    }
}
